In [30]:
import numpy as np

In [31]:
#create 1D array
arr=np.array([10,20,30,40,50,60,70,80,90])

In [32]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
#show first item
arr[0]

10

In [35]:
#show items between index 2 to 8(8 index is not included)
arr[2:8]

array([30, 40, 50, 60, 70, 80])

In [36]:
#show items between index 2 to end
arr[2:]

array([30, 40, 50, 60, 70, 80, 90])

In [37]:
#show items between index first to 7
arr[:8]

array([10, 20, 30, 40, 50, 60, 70, 80])

In [40]:
#show last item(Last item has index -1)
arr[-1]

90

In [41]:
#show last item(Last item has index -1)
arr[-2]

80

In [42]:
#show item present at index 2 and 3 (fancy indexing)
arr[[2,3]]

array([30, 40])

In [43]:
#show item present at index 1 and 7 (fancy indexing)
arr[[1,7]]

array([20, 80])