In [1]:
import numpy as np

In [29]:
# This file shows how to access 2 D array in numpy

In [15]:
#create array by using list items
arr=np.array([10,20,30,40,50,60,70,80,90])
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
#reshape array and convert to 3X3 matrix
arr=arr.reshape([3,3])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [18]:
#access first row
arr[0]

array([10, 20, 30])

In [19]:
#access row 0 and column 2 item
arr[0,2]

30

In [20]:
#access row 2 and column 2 item
arr[2,2]

90

In [21]:
#access all rows first column
arr[::,0]

array([10, 40, 70])

In [22]:
#fancy indexing. Access 0 and 2 rows
arr[[0,2]]

array([[10, 20, 30],
       [70, 80, 90]])

In [23]:
#fancy indexing. Access 2 and 1 rows
arr[[2,1]]

array([[70, 80, 90],
       [40, 50, 60]])

In [28]:
#display all rows in reverse order
arr[::-1,::]

array([[70, 80, 90],
       [40, 50, 60],
       [10, 20, 30]])