In [1]:
import numpy as np

In [ ]:
#computation on numpy array can be very fast or it can be slow
#the key to making it fast is to use vectorized operations. Generally impplemented through numpy's universal #function

In [3]:
def cal(arr1):
    temp=np.empty(len(arr1))
    for i in range(0,len(arr1)):
        temp[i]=1/arr[i]
    return temp


In [4]:
arr=np.arange(1,1000000)
%timeit cal(arr)

378 ms ± 6.73 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit 1/arr

4.18 ms ± 101 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
#Arithmatic universal function.
arr=np.arange(4)
arr

array([0, 1, 2, 3])

In [8]:
np.add(arr,5)

array([5, 6, 7, 8])

In [9]:
np.subtract(arr,5)

array([-5, -4, -3, -2])

In [11]:
np.power(arr,3)

array([ 0,  1,  8, 27], dtype=int32)

In [13]:
np.mod(arr,2)

array([0, 1, 0, 1], dtype=int32)

In [14]:
np.multiply(arr,5)

array([ 0,  5, 10, 15])

In [15]:
np.divide(arr,2)

array([0. , 0.5, 1. , 1.5])

In [16]:
np.square(arr)

array([0, 1, 4, 9], dtype=int32)

In [19]:
#Returns the lowest common multiple of |x1| and |x2|
np.lcm(12, 20)

60

In [20]:
np.lcm.reduce([3, 12, 20])

60

In [21]:
#Return the non-negative square-root of an array, element-wise.
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [26]:
#Returns the greatest common divisor of |x1| and |x2|
np.gcd(12, 20)

4

In [27]:
np.gcd.reduce([15, 25, 35])

5

In [28]:
#Return element-wise remainder of division.
np.remainder([4, 7], [2, 3])

array([0, 1], dtype=int32)

In [29]:
#Calculate the exponential of all elements in the input array.
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [31]:
#Calculate 2**p for all p in the input array.'
np.exp2(arr)

array([1., 2., 4., 8.])

In [32]:
#Natural logarithm, element-wise.
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229])

In [33]:
#Return the base 10 logarithm of the input array, element-wise.
np.log10(arr)

array([      -inf, 0.        , 0.30103   , 0.47712125])

In [34]:
#Base-2 logarithm of x.
np.log2(arr)

array([     -inf, 0.       , 1.       , 1.5849625])

In [39]:
#Calculate the absolute value element-wise.
x = np.array([-1.2, 1.2])
np.abs(x)

array([1.2, 1.2])

In [ ]:
#Trigonometric functions


In [42]:
#Trigonometric sine, element-wise. input Angle, in radians
arr2=np.array((0., 30., 45., 60., 90.)) 
arr2=arr2* np.pi / 180
arr2

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [48]:
r=np.sin(arr2)
r

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [49]:
#Inverse sine, element-wise.
np.arcsin(r)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [51]:
#Cosine element-wise.
r=np.cos(arr2)
r


array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [52]:
#Inverse cos, element-wise.
np.arccos(r)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [53]:
#Compute tangent element-wise.
r=np.tan(arr2)
r

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [54]:
#Inverse tan, element-wise.
np.arctan(r)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [55]:
#Convert angles from degrees to radians.
np.deg2rad(180)

3.141592653589793

In [56]:
#Convert angles from radians to degrees.
np.rad2deg(np.pi/2)

90.0