In [44]:
import numpy as np

In [54]:
#create Ndarray by using array function and order is Fortran(column major)
arr=np.array([[10,20],[30,40],[50,60]],dtype=float,order="F")
arr

array([[10., 20.],
       [30., 40.],
       [50., 60.]])

In [55]:
# this code show how column major store data in memory. K value does not change order
arr=arr.flatten(order='K')
arr

array([10., 30., 50., 20., 40., 60.])

In [56]:
#create array by using arange function
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [58]:
arr=np.arange(3)
arr

array([0, 1, 2])

In [20]:
#create array by using empty function
arr1=np.empty([3,3])
arr1

array([[6.52166653e-322, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 4.44659081e-321],
       [4.45044989e-307, 5.11793470e-307, 2.78147474e-307]])

In [22]:
#create array by using identity function
arr1=np.identity(3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
#create array by using ones function
arr1=np.ones([3,3])
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
#create array by using zeros function
arr1=np.zeros([3,3])
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
#create array by using full function
arr1=np.full([3,3],9)
arr1

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [26]:
#create array by using linspace function
arr1=np.linspace(1,10,20)
arr1

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [31]:
#create array by using mat function
arr1=np.mat('1 2;3 4')
arr1

matrix([[1, 2],
        [3, 4]])