In [41]:
import numpy as np


In [ ]:
#execution time required by list

In [46]:
%%time
mylist=list(range(1,100000))
temp=[]
for x in mylist:
    temp.append(x*x)


Wall time: 56 ms


In [ ]:
#execution time required by list

In [53]:
%%time
mylist=list(range(1,100000))
arr=np.array(mylist)
np.square(arr)

Wall time: 18 ms


In [ ]:
#using numpy array we can directly perofrm arithmatic operation on array.(without for loop)

In [55]:
arr1=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [56]:
arr2=np.array([[11,21,31],[41,51,61],[71,81,91]])
arr2

array([[11, 21, 31],
       [41, 51, 61],
       [71, 81, 91]])

In [57]:
arr1+arr2

array([[ 21,  41,  61],
       [ 81, 101, 121],
       [141, 161, 181]])

In [58]:
arr1*arr2

array([[ 110,  420,  930],
       [1640, 2550, 3660],
       [4970, 6480, 8190]])

In [59]:
arr1-arr2

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])